Fix the incompatibility issue of libwasmedge.0.dylib on macos x86_64
moxin-org/moly pull request #338
Opened 2024-12-31 06:39 UTC by yangcancai

## Fix the crash on macos x86_64
```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               _moly_app [22638]
Path:                  /Applications/Moly.app/Contents/MacOS/_moly_app
Identifier:            _moly_app
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Exited process [22637]
User ID:               501

Date/Time:             2024-12-31 11:29:13.7184 +0800
OS Version:            macOS 14.4.1 (23E224)
Report Version:        12
Bridge OS Version:     8.4 (21P4222)
Anonymous UUID:        38FD8E42-55B9-6552-B62A-10C3E31EE872

Sleep/Wake UUID:       A0EBF6FF-3DDF-4AB0-AF3A-BAF66E8CF9F7

Time Awake Since Boot: 990000 seconds
Time Since Wake:       11252 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/libwasmedge.0.dylib
Referenced from: <EE478A10-7904-3190-B4B7-50975A5D71B1> /Applications/Moly.app/Contents/MacOS/_moly_app
Reason: tried: '/Applications/Moly.app/Contents/Frameworks/libwasmedge.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/Applications/Moly.app/Contents/Frameworks/libwasmedge.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff8196c9b3e __abort_with_payload + 10
1   dyld                          	    0x7ff8196e2bb7 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff8196e2be9 abort_with_payload + 9
3   dyld                          	    0x7ff81966f2e5 dyld4::halt(char const*, dyld4::StructuredError const*) + 335
4   dyld                          	    0x7ff81966c4e2 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4099
5   dyld                          	    0x7ff81966b2ff start + 1839

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000001  rcx: 0x00007ff7bfbd9578  rdx: 0x00007ff7bfbd99e0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bfbd95c0  rsp: 0x00007ff7bfbd9578
   r8: 0x00007ff7bfbd95e0   r9: 0x0000000000000000  r10: 0x000000000000005f  r11: 0x0000000000000246
  r12: 0x0000000000000000  r13: 0x00007ff7bfbd99e0  r14: 0x0000000000000006  r15: 0x000000000000005f
  rip: 0x00007ff8196c9b3e  rfl: 0x0000000000000246  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133
```

2024-12-31 06:50 UTC, L-jasmine commented
LGTM

2024-12-31 07:18 UTC, kevinaboos requested changes
Semantically it's fine, but I left a few small questions.

2024-12-31 07:18 UTC, kevinaboos commented on packaging/before-packaging-command/src/main.rs
> +    if std::env::consts::ARCH == "x86_64" {
Don't we need to check the *target* architecture, not the architecture of the build machine? This assumes we never do any cross compilation and only build for the current arch.

2024-12-31 07:18 UTC, kevinaboos commented on packaging/before-packaging-command/src/main.rs
> +    let mut wasmedge_download_url = String::new();
the canonically Rusty way to do this is to either declare a variable without initializing it, or return a tuple from the following block.
You can just do:
```rust
let wasmedge_download_url: String;
let wasi_nn_download_url: String;
```

2024-12-31 07:18 UTC, kevinaboos commented on packaging/before-packaging-command/src/main.rs
> +    if std::env::consts::ARCH == "x86_64" {
Or, at the very least, allow it to be overridden with a CLI arg or env var.

2025-01-01 01:33 UTC, yangcancai commented on packaging/before-packaging-command/src/main.rs
> +    if std::env::consts::ARCH == "x86_64" {
Got it, will changed it the same with host_os.

2025-01-01 18:56 UTC, kevinaboos commented
Ok the code looks good now. Shouldn't we also document how to use this new `arch` argument, both in the code and in the Readme section about packaging? Otherwise it's unlikely that anyone will correctly use it.

Also, just to clarify, this seems to be only intended to support macOS x86_64 builds, right? If so, we should state that explicitly in the docs.

2025-01-02 01:31 UTC, yangcancai commented
`cargo packager --release` seems unable to pass arg. because `before-packaging-command` is hardcoded in Cargo.toml. Is it possible to use env instead?
For example, `ARCH=x86_64 cargo packager --release` passes arch, which can be obtained through `env::var("ARCH")` in the code.

2025-01-02 05:10 UTC, kevinaboos commented
Correct, you would not pass these arguments to the invocation of `cargo-packager` itself. You would add them into the invocation of the `before-packaging-command`, which is defined in the Cargo.toml file. 

But yes, and env var is fine too.

2025-01-02 05:12 UTC, kevinaboos commented
You shouldn't actually even need this to be a CLI arg or env var. Can't you just take it from the target spec? That is, if you're building for an aarch64 target, you'll already know that at the cargo and rust layer, based on the target triple selected at build time. So you can just use `cfg(target_arch)`, right?

2025-01-02 10:05 UTC, yangcancai commented
Nice, I agree with you, using cfg(target_arch) will be more rusty.

2025-01-03 07:38 UTC, kevinaboos approved these changes
Looks great! 

I haven't tested the code myself, so I won't merge it in, but will approve these changes.

2025-01-15 16:21 UTC, merged